/**
 * Bulk Seed Products for All Categories
 * Realistic Pakistani market prices & accurate plant data
 */
const { initializeApp } = require('firebase/app');
const { getFirestore, collection, addDoc } = require('firebase/firestore');

const app = initializeApp({
    apiKey: "AIzaSyCccVpOYTW2xLXfB2tWVqjJ9VCSTl5SuZY",
    authDomain: "gardenmate-3e7c5.firebaseapp.com",
    projectId: "gardenmate-3e7c5",
    storageBucket: "gardenmate-3e7c5.firebasestorage.app",
    messagingSenderId: "429528664912",
    appId: "1:429528664912:web:9b7f02104bb744ce697a55"
});
const db = getFirestore(app);

const VENDOR_ID = "BZUhKXZ1yPY9Iav4YsrFHl2cATu1"; // Pattoki gardens

const allProducts = [

    // ===== INDOOR (3 more to complement existing 4) =====
    {
        name: "Rubber Plant (Ficus Elastica)",
        description: "A classic indoor plant with thick, glossy dark green leaves. The Rubber Plant is known for its bold appearance and air-purifying qualities. It can grow up to 6-10 feet indoors and requires minimal care, making it perfect for homes and offices.",
        price: 1800,
        category: "Indoor",
        productType: "plant",
        stock: 18,
        image: "https://images.unsplash.com/photo-1632207691143-643e1e52f1fd?w=600",
        images: ["https://images.unsplash.com/photo-1632207691143-643e1e52f1fd?w=600"],
        tags: ["Indoor", "Air Purifying", "Low Maintenance"],
        careInfo: { water: "Weekly", light: "Bright Indirect", temperature: "16-30°C" },
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "Pothos (Money Plant)",
        description: "The most popular trailing houseplant in Pakistan. Pothos features heart-shaped leaves with golden variegation. Extremely hardy and adaptable, it grows in both water and soil. Excellent for shelves, hanging baskets, and offices. Known to bring good luck and prosperity.",
        price: 500,
        category: "Indoor",
        productType: "plant",
        stock: 50,
        image: "https://images.unsplash.com/photo-1572688484438-313a56e6dc34?w=600",
        images: ["https://images.unsplash.com/photo-1572688484438-313a56e6dc34?w=600"],
        tags: ["Indoor", "Beginner", "Air Purifying"],
        careInfo: { water: "Weekly", light: "Low to Bright", temperature: "15-35°C" },
        discount: 10,
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "ZZ Plant (Zamioculcas)",
        description: "One of the toughest houseplants available. The ZZ Plant has waxy, dark green leaves that look almost artificial. It tolerates low light, infrequent watering, and neglect. Ideal for beginners, offices, and air-conditioned rooms. Grows slowly but steadily.",
        price: 2000,
        category: "Indoor",
        productType: "plant",
        stock: 12,
        image: "https://images.unsplash.com/photo-1632207691143-643e1e52f1fd?w=600",
        images: ["https://images.unsplash.com/photo-1632207691143-643e1e52f1fd?w=600"],
        tags: ["Indoor", "Low Maintenance", "Beginner"],
        careInfo: { water: "Biweekly", light: "Low to Indirect", temperature: "15-30°C" },
        freeShipping: false, shippingDays: "3-5",
    },

    // ===== FLOWERS (7 products) =====
    {
        name: "Red Rose Bush",
        description: "The classic Red Rose, Pakistan's most beloved flowering plant. This grafted bush produces large, fragrant blooms throughout spring and autumn. Perfect for gardens, borders, and pots. Requires full sun and regular watering for best flowering.",
        price: 800,
        category: "Flowers",
        productType: "plant",
        stock: 25,
        image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600",
        images: ["https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600"],
        tags: ["Flowering", "Outdoor"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "15-35°C" },
        freeShipping: false, shippingDays: "2-4",
    },
    {
        name: "Jasmine (Motia)",
        description: "Pakistan's national flower, known for its intoxicating fragrance. Motia Jasmine produces small white star-shaped flowers from spring through autumn. Popular for garlands, perfumes, and traditional medicine. A must-have for every Pakistani garden.",
        price: 600,
        category: "Flowers",
        productType: "plant",
        stock: 30,
        image: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600",
        images: ["https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600"],
        tags: ["Flowering", "Fragrant"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "18-38°C" },
        discount: 15,
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Hibiscus (Gul-e-Daoodi)",
        description: "A vibrant tropical flowering plant that produces large, colorful blooms in red, pink, yellow, and orange. Hibiscus thrives in Pakistan's warm climate and blooms year-round. Great for hedges, pots, and garden borders. Attracts butterflies and hummingbirds.",
        price: 700,
        category: "Flowers",
        productType: "plant",
        stock: 20,
        image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600",
        images: ["https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600"],
        tags: ["Flowering", "Tropical"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "20-38°C" },
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Marigold (Genda)",
        description: "One of Pakistan's most popular seasonal flowers. Marigolds produce bright yellow and orange blooms that last for months. Widely used in weddings, festivals, and religious ceremonies. Easy to grow from seed and excellent for pest control in vegetable gardens.",
        price: 250,
        category: "Flowers",
        productType: "plant",
        stock: 40,
        image: "https://images.unsplash.com/photo-1598187076373-217a3acdc001?w=600",
        images: ["https://images.unsplash.com/photo-1598187076373-217a3acdc001?w=600"],
        tags: ["Flowering", "Beginner", "Seasonal"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "18-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Sunflower Plant",
        description: "Bright, cheerful sunflowers that follow the sun throughout the day. These tall, striking plants produce large golden blooms and edible seeds. Easy to grow in Pakistani climate. Perfect for garden borders and as cut flowers.",
        price: 350,
        category: "Flowers",
        productType: "plant",
        stock: 35,
        image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600",
        images: ["https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600"],
        tags: ["Flowering", "Beginner"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "20-35°C" },
        freeShipping: true, shippingDays: "2-4",
    },
    {
        name: "Night Blooming Jasmine (Raat Ki Rani)",
        description: "Famous for its powerful, sweet fragrance that fills the evening air. Raat Ki Rani blooms at night and is a staple in many Pakistani homes. The small white flowers attract moths and add a magical atmosphere to gardens and terraces.",
        price: 900,
        category: "Flowers",
        productType: "plant",
        stock: 15,
        image: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600",
        images: ["https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600"],
        tags: ["Flowering", "Fragrant"],
        careInfo: { water: "Twice Weekly", light: "Partial Sun", temperature: "18-35°C" },
        discount: 20,
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Dahlia Mixed Colors",
        description: "Gorgeous dahlia tubers that produce stunning multi-layered blooms in a variety of colors including red, pink, purple, and white. Dahlias are prized for their show-stopping flowers and are perfect for borders and cutting gardens. Bloom from late summer through autumn.",
        price: 450,
        category: "Flowers",
        productType: "plant",
        stock: 22,
        image: "https://images.unsplash.com/photo-1598187076373-217a3acdc001?w=600",
        images: ["https://images.unsplash.com/photo-1598187076373-217a3acdc001?w=600"],
        tags: ["Flowering", "Seasonal"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "15-30°C" },
        freeShipping: true, shippingDays: "3-5",
    },

    // ===== FRUITS (7 products) =====
    {
        name: "Mango Tree (Chaunsa Grafted)",
        description: "Premium Chaunsa variety grafted mango tree, Pakistan's most prized mango. This grafted sapling will start fruiting within 2-3 years. Chaunsa mangoes are known for their exceptional sweetness, rich aroma, and fiber-free flesh. Suitable for gardens and large pots.",
        price: 3500,
        category: "Fruits",
        productType: "plant",
        stock: 8,
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600",
        images: ["https://images.unsplash.com/photo-1553279768-865429fa0078?w=600"],
        tags: ["Fruit Tree", "Grafted"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "25-45°C" },
        discount: 10,
        freeShipping: false, shippingDays: "5-7",
    },
    {
        name: "Guava Tree (Amrood)",
        description: "A fast-growing, evergreen fruit tree that produces sweet, vitamin-C-rich guavas year-round in Pakistan's climate. This grafted sapling begins fruiting within 1-2 years. Guava is one of the easiest fruit trees to grow and requires minimal care.",
        price: 1200,
        category: "Fruits",
        productType: "plant",
        stock: 15,
        image: "https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=600",
        images: ["https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=600"],
        tags: ["Fruit Tree", "Beginner"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "20-40°C" },
        freeShipping: false, shippingDays: "4-6",
    },
    {
        name: "Lemon Tree (Nimbu)",
        description: "An essential kitchen garden tree that produces juicy lemons throughout the year. This grafted dwarf variety is perfect for pots and small gardens. Pakistani lemons are known for their strong flavor and aromatic zest. Bears fruit within the first year.",
        price: 1500,
        category: "Fruits",
        productType: "plant",
        stock: 20,
        image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600",
        images: ["https://images.unsplash.com/photo-1590502593747-42a996133562?w=600"],
        tags: ["Fruit Tree", "Compact"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "18-38°C" },
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "Pomegranate Tree (Anaar)",
        description: "A beautiful ornamental and fruit-bearing tree. Pomegranates thrive in Pakistan's climate and produce ruby-red fruits packed with antioxidants. The tree also has attractive orange-red flowers. Drought-tolerant once established.",
        price: 2000,
        category: "Fruits",
        productType: "plant",
        stock: 10,
        image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600",
        images: ["https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600"],
        tags: ["Fruit Tree", "Drought Tolerant"],
        careInfo: { water: "Weekly", light: "Full Sun", temperature: "20-42°C" },
        discount: 15,
        freeShipping: false, shippingDays: "4-6",
    },
    {
        name: "Banana Plant (Kela)",
        description: "A tropical fruit plant that grows quickly in Pakistan's warm climate. This dwarf Cavendish variety is perfect for home gardens and produces sweet, medium-sized bananas. The large, dramatic leaves also make it an excellent ornamental plant.",
        price: 1800,
        category: "Fruits",
        productType: "plant",
        stock: 12,
        image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600",
        images: ["https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600"],
        tags: ["Fruit Tree", "Tropical"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "22-38°C" },
        freeShipping: false, shippingDays: "5-7",
    },
    {
        name: "Papaya Plant",
        description: "A fast-growing tropical fruit plant that starts fruiting within 6-8 months. Papayas are rich in vitamins A and C, and the plant grows well in Pakistan's Punjab and Sindh regions. Requires warm weather and protection from frost.",
        price: 800,
        category: "Fruits",
        productType: "plant",
        stock: 18,
        image: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=600",
        images: ["https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=600"],
        tags: ["Fruit Tree", "Fast Growing"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "25-40°C" },
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "Fig Tree (Anjeer)",
        description: "A drought-tolerant fruit tree that produces sweet, nutritious figs. Anjeer is highly valued in Pakistan for its health benefits including high fiber, potassium, and calcium content. The tree adapts well to containers and garden beds alike.",
        price: 2500,
        category: "Fruits",
        productType: "plant",
        stock: 7,
        image: "https://images.unsplash.com/photo-1601379329542-31c59347e2b8?w=600",
        images: ["https://images.unsplash.com/photo-1601379329542-31c59347e2b8?w=600"],
        tags: ["Fruit Tree", "Drought Tolerant"],
        careInfo: { water: "Weekly", light: "Full Sun", temperature: "18-40°C" },
        freeShipping: false, shippingDays: "4-6",
    },

    // ===== VEGETABLES (7 products) =====
    {
        name: "Tomato Plant (Tamatar)",
        description: "Fresh, healthy tomato seedlings ready for transplanting. Produces juicy, red tomatoes within 60-80 days. Tomatoes are a kitchen essential in Pakistani cuisine. Grows well in pots, raised beds, and garden soil. Multiple harvests per season.",
        price: 150,
        category: "Vegetables",
        productType: "plant",
        stock: 60,
        image: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600",
        images: ["https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600"],
        tags: ["Vegetable", "Beginner", "Kitchen Garden"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "20-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Green Chili Plant (Hari Mirch)",
        description: "Essential for every Pakistani kitchen garden. These healthy chili seedlings produce abundant, spicy green chilies within 45-60 days. Grows easily in pots on balconies and terraces. One plant can produce continuously for 6+ months.",
        price: 120,
        category: "Vegetables",
        productType: "plant",
        stock: 50,
        image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600",
        images: ["https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600"],
        tags: ["Vegetable", "Beginner", "Kitchen Garden"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "22-38°C" },
        discount: 10,
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Cucumber Plant (Kheera)",
        description: "Crisp, refreshing cucumber seedlings perfect for summer growing. Produces tender, juicy cucumbers within 50-60 days. A salad essential in Pakistani households. Grows well on trellises and in raised beds.",
        price: 180,
        category: "Vegetables",
        productType: "plant",
        stock: 35,
        image: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600",
        images: ["https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600"],
        tags: ["Vegetable", "Summer", "Kitchen Garden"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "22-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Spinach Seedlings (Palak)",
        description: "Nutritious spinach seedlings ready for transplanting. Palak is one of Pakistan's most consumed leafy greens, used in countless dishes from palak paneer to soups. Fast-growing, harvest-ready in 30-40 days. Grows well in winter season.",
        price: 100,
        category: "Vegetables",
        productType: "plant",
        stock: 45,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600",
        images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600"],
        tags: ["Vegetable", "Leafy Green", "Winter"],
        careInfo: { water: "Regular", light: "Partial Sun", temperature: "10-25°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Bitter Gourd Plant (Karela)",
        description: "A climbing vegetable plant that produces bitter gourds, prized in Pakistani cuisine for their unique flavor and medicinal properties. Known to help regulate blood sugar. Grows on trellises and fences.",
        price: 200,
        category: "Vegetables",
        productType: "plant",
        stock: 25,
        image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600",
        images: ["https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600"],
        tags: ["Vegetable", "Climbing", "Medicinal"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "25-38°C" },
        freeShipping: true, shippingDays: "2-4",
    },
    {
        name: "Okra Plant (Bhindi)",
        description: "Pakistan's favorite summer vegetable. These healthy okra seedlings produce tender, green lady fingers within 50-60 days. Bhindi is a staple in Pakistani cooking. Easy to grow in warm weather with full sun.",
        price: 130,
        category: "Vegetables",
        productType: "plant",
        stock: 40,
        image: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600",
        images: ["https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600"],
        tags: ["Vegetable", "Summer", "Kitchen Garden"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "25-40°C" },
        discount: 15,
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Eggplant (Baingan)",
        description: "A versatile vegetable plant that produces glossy purple eggplants. Essential for making baingan ka bharta, a beloved Pakistani dish. These seedlings are ready for transplanting and will fruit within 60-75 days. Grows well in warm weather.",
        price: 160,
        category: "Vegetables",
        productType: "plant",
        stock: 30,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600",
        images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600"],
        tags: ["Vegetable", "Summer", "Kitchen Garden"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "22-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },

    // ===== HERBS (7 products) =====
    {
        name: "Mint Plant (Pudina)",
        description: "Aromatic, fast-growing mint essential for Pakistani drinks and chutneys. Fresh pudina is used in raita, chutney, mojitos, and traditional remedies. Grows vigorously in pots and garden beds. One plant provides continuous harvests for months.",
        price: 250,
        category: "Herbs",
        productType: "plant",
        stock: 40,
        image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600",
        images: ["https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600"],
        tags: ["Herb", "Kitchen Garden", "Beginner"],
        careInfo: { water: "Daily", light: "Partial Sun", temperature: "15-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Coriander Plant (Dhaniya)",
        description: "Pakistan's most used herb in cooking. Fresh dhaniya is essential for garnishing curries, salsas, and chutneys. Fast-growing, harvest-ready in 3-4 weeks. Grows well in pots on balconies and windowsills, especially in cooler months.",
        price: 150,
        category: "Herbs",
        productType: "plant",
        stock: 50,
        image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600",
        images: ["https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600"],
        tags: ["Herb", "Kitchen Garden", "Beginner"],
        careInfo: { water: "Regular", light: "Partial Sun", temperature: "10-30°C" },
        discount: 10,
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Basil Plant (Niazbo)",
        description: "Sweet basil, known as Niazbo in Pakistan, is prized for its aromatic leaves used in Italian and Asian cuisines. Also used in traditional medicine for digestive and anti-inflammatory benefits. Compact and perfect for windowsill gardening.",
        price: 300,
        category: "Herbs",
        productType: "plant",
        stock: 30,
        image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600",
        images: ["https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600"],
        tags: ["Herb", "Aromatic", "Kitchen Garden"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "20-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Aloe Vera",
        description: "A medicinal succulent used for skin care, burns, and digestive health. Aloe Vera gel is widely used in Pakistani households for face masks, hair treatments, and sunburn relief. Extremely low maintenance — perfect for beginners.",
        price: 400,
        category: "Herbs",
        productType: "plant",
        stock: 35,
        image: "https://images.unsplash.com/photo-1567331711402-509c12c41959?w=600",
        images: ["https://images.unsplash.com/photo-1567331711402-509c12c41959?w=600"],
        tags: ["Herb", "Medicinal", "Low Maintenance"],
        careInfo: { water: "Biweekly", light: "Bright Indirect", temperature: "15-40°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Lemongrass (Hari Chai)",
        description: "A fragrant herb widely used for making herbal tea (hari chai) in Pakistan. Lemongrass has a refreshing citrusy flavor and is known for its digestive and calming properties. Grows in clumps and also acts as a natural mosquito repellent.",
        price: 350,
        category: "Herbs",
        productType: "plant",
        stock: 20,
        image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600",
        images: ["https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600"],
        tags: ["Herb", "Aromatic", "Medicinal"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "20-40°C" },
        discount: 20,
        freeShipping: true, shippingDays: "2-4",
    },
    {
        name: "Curry Leaf Plant (Kari Patta)",
        description: "An essential aromatic herb in Pakistani and South Asian cooking. Fresh curry leaves add an irreplaceable flavor to dals, curries, and rice dishes. The plant grows into a small tree over time and produces fragrant leaves year-round.",
        price: 500,
        category: "Herbs",
        productType: "plant",
        stock: 15,
        image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600",
        images: ["https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600"],
        tags: ["Herb", "Aromatic", "Kitchen Garden"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "20-38°C" },
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Rosemary Plant",
        description: "A woody, fragrant herb popular in Mediterranean and modern Pakistani cuisine. Rosemary adds incredible flavor to grilled meats, bread, and roasted vegetables. Drought-tolerant and compact, perfect for pots and kitchen gardens.",
        price: 550,
        category: "Herbs",
        productType: "plant",
        stock: 18,
        image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600",
        images: ["https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600"],
        tags: ["Herb", "Aromatic", "Drought Tolerant"],
        careInfo: { water: "Weekly", light: "Full Sun", temperature: "15-30°C" },
        freeShipping: true, shippingDays: "3-5",
    },

    // ===== CLIMBERS (7 products) =====
    {
        name: "Bougainvillea",
        description: "Pakistan's most popular climbing plant, known for its spectacular display of vibrant pink, purple, red, or orange bracts. Bougainvillea is drought-tolerant and thrives on walls, fences, and pergolas. Blooms profusely in warm weather and requires minimal care once established.",
        price: 900,
        category: "Climbers",
        productType: "plant",
        stock: 15,
        image: "https://images.unsplash.com/photo-1596438459194-f275f413d6ff?w=600",
        images: ["https://images.unsplash.com/photo-1596438459194-f275f413d6ff?w=600"],
        tags: ["Climbing", "Flowering", "Drought Tolerant"],
        careInfo: { water: "Weekly", light: "Full Sun", temperature: "20-40°C" },
        discount: 10,
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Star Jasmine (Chameli)",
        description: "A fragrant evergreen climber that produces clusters of white, star-shaped flowers. Chameli is a beloved plant in Pakistani homes, grown on walls, trellises, and arches. The sweet scent fills the garden on warm evenings. Grows quickly and stays green year-round.",
        price: 750,
        category: "Climbers",
        productType: "plant",
        stock: 20,
        image: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600",
        images: ["https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600"],
        tags: ["Climbing", "Fragrant", "Evergreen"],
        careInfo: { water: "Regular", light: "Full to Partial Sun", temperature: "15-35°C" },
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "English Ivy",
        description: "A classic evergreen climbing plant that attaches to walls using aerial rootlets. English Ivy is excellent for covering walls, fences, and ground cover. It creates a lush, green look and also purifies indoor air. Very low maintenance.",
        price: 450,
        category: "Climbers",
        productType: "plant",
        stock: 25,
        image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600",
        images: ["https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600"],
        tags: ["Climbing", "Evergreen", "Air Purifying"],
        careInfo: { water: "Twice Weekly", light: "Partial Shade", temperature: "10-30°C" },
        freeShipping: true, shippingDays: "2-4",
    },
    {
        name: "Passion Flower Vine",
        description: "An exotic climber producing stunning purple and white flowers, followed by edible passion fruit. Fast-growing and perfect for covering trellises and fences. The intricate flowers are a conversation starter in any garden.",
        price: 1200,
        category: "Climbers",
        productType: "plant",
        stock: 10,
        image: "https://images.unsplash.com/photo-1596438459194-f275f413d6ff?w=600",
        images: ["https://images.unsplash.com/photo-1596438459194-f275f413d6ff?w=600"],
        tags: ["Climbing", "Flowering", "Fruit Bearing"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "18-35°C" },
        discount: 15,
        freeShipping: false, shippingDays: "4-6",
    },
    {
        name: "Morning Glory (Petunia Vine)",
        description: "A fast-growing annual vine that produces trumpet-shaped flowers in blue, purple, pink, and white every morning. Easy to grow from seed, Morning Glory covers fences and walls quickly. A beautiful, low-cost way to add color to any garden.",
        price: 300,
        category: "Climbers",
        productType: "plant",
        stock: 30,
        image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600",
        images: ["https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600"],
        tags: ["Climbing", "Flowering", "Beginner"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "20-35°C" },
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Madhumalti (Rangoon Creeper)",
        description: "A stunning climbing plant whose flowers change color from white to pink to deep red as they mature. Very popular in Pakistani gardens for covering pergolas and archways. Blooms have a sweet fragrance, especially in the evening.",
        price: 850,
        category: "Climbers",
        productType: "plant",
        stock: 12,
        image: "https://images.unsplash.com/photo-1596438459194-f275f413d6ff?w=600",
        images: ["https://images.unsplash.com/photo-1596438459194-f275f413d6ff?w=600"],
        tags: ["Climbing", "Flowering", "Fragrant"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "20-40°C" },
        freeShipping: false, shippingDays: "3-5",
    },

    // ===== SEEDS (7 products) =====
    {
        name: "Tomato Seeds Pack",
        description: "High-quality hybrid tomato seeds suitable for Pakistani climate. Each pack contains 50+ seeds with 90%+ germination rate. Produces large, juicy red tomatoes. Sow in winter season (October-February) for best results.",
        price: 150,
        category: "Seeds",
        productType: "seeds",
        stock: 100,
        image: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600",
        images: ["https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600"],
        tags: ["Seeds", "Vegetable", "Kitchen Garden"],
        careInfo: { water: "Keep Moist", light: "Full Sun", temperature: "20-30°C" },
        freeShipping: true, shippingDays: "1-2",
    },
    {
        name: "Sunflower Seeds Pack",
        description: "Premium sunflower seeds — both ornamental and edible varieties. Pack of 30+ seeds. These tall, stunning flowers brighten any garden and the seeds can be harvested for snacking. Easy to grow, perfect for kids' gardening projects.",
        price: 120,
        category: "Seeds",
        productType: "seeds",
        stock: 80,
        image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600",
        images: ["https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600"],
        tags: ["Seeds", "Flower", "Beginner"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "20-35°C" },
        discount: 20,
        freeShipping: true, shippingDays: "1-2",
    },
    {
        name: "Mixed Herb Seeds Kit",
        description: "A complete herb garden starter kit with seeds for Mint, Basil, Coriander, Dill, and Parsley. 5 seed packets in one box with growing instructions. Perfect gift for kitchen garden enthusiasts.",
        price: 450,
        category: "Seeds",
        productType: "seeds",
        stock: 40,
        image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600",
        images: ["https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600"],
        tags: ["Seeds", "Herb", "Gift Set"],
        careInfo: { water: "Keep Moist", light: "Partial Sun", temperature: "15-30°C" },
        freeShipping: true, shippingDays: "1-2",
    },
    {
        name: "Watermelon Seeds Pack",
        description: "Premium watermelon seeds for growing sweet, juicy watermelons at home. Contains 25+ seeds of the Sugar Baby variety — compact melons perfect for home gardens. Sow in spring for summer harvest.",
        price: 180,
        category: "Seeds",
        productType: "seeds",
        stock: 60,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600",
        images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600"],
        tags: ["Seeds", "Fruit", "Summer"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "25-38°C" },
        freeShipping: true, shippingDays: "1-2",
    },
    {
        name: "Marigold Seeds Pack",
        description: "Bright, vibrant marigold seeds — a mix of yellow and orange varieties. Pack of 100+ seeds with excellent germination. Marigolds bloom quickly and deter pests naturally. Perfect for borders and companion planting.",
        price: 100,
        category: "Seeds",
        productType: "seeds",
        stock: 90,
        image: "https://images.unsplash.com/photo-1598187076373-217a3acdc001?w=600",
        images: ["https://images.unsplash.com/photo-1598187076373-217a3acdc001?w=600"],
        tags: ["Seeds", "Flower", "Beginner"],
        careInfo: { water: "Regular", light: "Full Sun", temperature: "18-35°C" },
        freeShipping: true, shippingDays: "1-2",
    },
    {
        name: "Chili Seeds Variety Pack",
        description: "A collection of 4 popular chili varieties: Green Chili, Red Chili, Capsicum, and Bird's Eye. 30+ seeds per variety. Essential for every Pakistani kitchen garden. High germination rate.",
        price: 250,
        category: "Seeds",
        productType: "seeds",
        stock: 55,
        image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600",
        images: ["https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600"],
        tags: ["Seeds", "Vegetable", "Kitchen Garden"],
        careInfo: { water: "Keep Moist", light: "Full Sun", temperature: "22-38°C" },
        discount: 10,
        freeShipping: true, shippingDays: "1-2",
    },
    {
        name: "Lawn Grass Seeds (1 kg)",
        description: "Premium lawn grass seed mix suitable for Pakistani climate. Contains a blend of Bermuda and Fescue varieties for a lush, green lawn year-round. Coverage: approximately 500 sq ft. Includes growing instructions.",
        price: 800,
        category: "Seeds",
        productType: "seeds",
        stock: 25,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600",
        images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600"],
        tags: ["Seeds", "Lawn", "Ground Cover"],
        careInfo: { water: "Daily", light: "Full Sun", temperature: "15-35°C" },
        freeShipping: false, shippingDays: "2-4",
    },

    // ===== POTS (7 products) =====
    {
        name: "Terracotta Clay Pot (Medium)",
        description: "Traditional Pakistani clay pot, hand-made by local artisans. Terracotta is ideal for plants as it allows air and moisture to pass through the walls, keeping roots healthy. Diameter: 8 inches. Natural, eco-friendly material.",
        price: 350,
        category: "Pots",
        productType: "accessory",
        stock: 50,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
        tags: ["Pot", "Clay", "Traditional"],
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Ceramic Glazed Pot (White)",
        description: "Elegant white ceramic pot with a glossy glaze finish. Perfect for indoor plants like Snake Plants and Peace Lilies. Includes drainage hole and saucer. Diameter: 6 inches. Modern design suits contemporary interiors.",
        price: 1200,
        category: "Pots",
        productType: "accessory",
        stock: 25,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
        tags: ["Pot", "Ceramic", "Indoor"],
        discount: 15,
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Hanging Macrame Planter",
        description: "Handcrafted macrame plant hanger made from natural cotton rope. Perfect for trailing plants like Pothos and String of Pearls. Adds a bohemian touch to any room or balcony. Fits pots up to 6 inches diameter.",
        price: 800,
        category: "Pots",
        productType: "accessory",
        stock: 20,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
        tags: ["Pot", "Hanging", "Decorative"],
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "Large Fiber Pot (12 inch)",
        description: "Lightweight yet durable fiber pot, ideal for large plants and trees. Made from recycled fiber material, it's eco-friendly and weather-resistant. Diameter: 12 inches. Perfect for Fiddle Leaf Figs, Monstera, and fruit trees.",
        price: 900,
        category: "Pots",
        productType: "accessory",
        stock: 18,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
        tags: ["Pot", "Large", "Eco-Friendly"],
        freeShipping: false, shippingDays: "4-6",
    },
    {
        name: "Self-Watering Pot (Smart Pot)",
        description: "Modern self-watering pot with a built-in reservoir that keeps plants hydrated for up to 2 weeks. Perfect for busy plant parents and office plants. Includes water level indicator. Diameter: 7 inches.",
        price: 1500,
        category: "Pots",
        productType: "accessory",
        stock: 12,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
        tags: ["Pot", "Smart", "Indoor"],
        discount: 10,
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "Seedling Tray (72 Cells)",
        description: "Professional seedling starter tray with 72 individual cells. Made from durable plastic with drainage holes. Perfect for starting seeds indoors before transplanting. Reusable for multiple seasons.",
        price: 400,
        category: "Pots",
        productType: "accessory",
        stock: 30,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
        images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600"],
        tags: ["Pot", "Seedling", "Professional"],
        freeShipping: true, shippingDays: "2-3",
    },

    // ===== FERTILIZERS (7 products) =====
    {
        name: "Organic Compost (5 kg)",
        description: "Premium organic compost made from decomposed plant matter and farm waste. Rich in essential nutrients and beneficial microorganisms. Improves soil structure, water retention, and plant growth. Safe for all plants including edibles.",
        price: 500,
        category: "Fertilizers",
        productType: "accessory",
        stock: 40,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Fertilizer", "Organic", "Soil"],
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "NPK 20-20-20 Fertilizer (1 kg)",
        description: "All-purpose balanced NPK fertilizer suitable for all plants. Contains equal parts Nitrogen, Phosphorus, and Potassium for complete nutrition. Water-soluble formula for easy application. Use fortnightly for best results.",
        price: 650,
        category: "Fertilizers",
        productType: "accessory",
        stock: 35,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Fertilizer", "Chemical", "All-Purpose"],
        discount: 10,
        freeShipping: false, shippingDays: "2-4",
    },
    {
        name: "Vermicompost (3 kg)",
        description: "Premium earthworm castings — nature's best fertilizer. Vermicompost is packed with beneficial bacteria, enzymes, and humic acid. It enriches soil, promotes root growth, and enhances plant immunity. 100% organic and odorless.",
        price: 450,
        category: "Fertilizers",
        productType: "accessory",
        stock: 25,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Fertilizer", "Organic", "Premium"],
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "DAP Fertilizer (1 kg)",
        description: "Di-Ammonium Phosphate — a high-phosphorus fertilizer ideal for flowering and fruiting plants. Promotes strong root development and abundant blooms. Essential for rose bushes, fruit trees, and flowering plants.",
        price: 350,
        category: "Fertilizers",
        productType: "accessory",
        stock: 30,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Fertilizer", "Chemical", "Flowering"],
        freeShipping: false, shippingDays: "2-4",
    },
    {
        name: "Bone Meal Organic (2 kg)",
        description: "Natural bone meal fertilizer rich in phosphorus and calcium. Excellent for flowering plants, bulbs, and root vegetables. Slow-release formula provides nutrients for up to 4 months. 100% organic, made from sterilized animal bones.",
        price: 400,
        category: "Fertilizers",
        productType: "accessory",
        stock: 20,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Fertilizer", "Organic", "Slow Release"],
        discount: 15,
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Neem Cake Fertilizer (2 kg)",
        description: "Natural neem cake — a dual-purpose product that acts as both fertilizer and pest repellent. Rich in nitrogen and micronutrients. Protects roots from nematodes and soil-borne pests. Very popular among organic farmers in Pakistan.",
        price: 350,
        category: "Fertilizers",
        productType: "accessory",
        stock: 28,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Fertilizer", "Organic", "Pest Control"],
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Potting Mix Premium (5 kg)",
        description: "Ready-to-use potting mix blend with peat moss, perlite, vermiculite, and organic compost. Provides excellent drainage and aeration for potted plants. pH balanced and nutrient-enriched. Suitable for indoor and outdoor container plants.",
        price: 600,
        category: "Fertilizers",
        productType: "accessory",
        stock: 22,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Soil", "Potting Mix", "Premium"],
        freeShipping: false, shippingDays: "3-5",
    },

    // ===== ACCESSORIES (6 products, 1 already exists: Watering Cans) =====
    {
        name: "Garden Tool Set (5 Piece)",
        description: "Complete garden tool set including trowel, transplanter, weeder, cultivator, and fork. Made from rust-resistant stainless steel with comfortable rubber grips. Ideal for potting, planting, and general garden maintenance.",
        price: 1500,
        category: "Accessories",
        productType: "accessory",
        stock: 20,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Tools", "Garden", "Starter Kit"],
        discount: 10,
        freeShipping: true, shippingDays: "3-5",
    },
    {
        name: "Garden Spray Bottle (1L)",
        description: "Adjustable nozzle spray bottle for misting indoor plants and applying liquid fertilizers. 1-liter capacity with comfortable trigger grip. Settings range from fine mist to steady stream. Essential for humidity-loving plants.",
        price: 350,
        category: "Accessories",
        productType: "accessory",
        stock: 35,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Tools", "Watering", "Indoor"],
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Plant Support Sticks (Pack of 10)",
        description: "Bamboo plant support sticks for climbing and trailing plants. 3 feet tall, natural bamboo material. Perfect for supporting tomatoes, cucumbers, money plants, and other vining plants. Eco-friendly and biodegradable.",
        price: 250,
        category: "Accessories",
        productType: "accessory",
        stock: 40,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Support", "Bamboo", "Eco-Friendly"],
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Gardening Gloves (Pair)",
        description: "Durable, breathable gardening gloves with reinforced fingertips. Protects hands from thorns, soil, and rough surfaces. Water-resistant coating on palms for wet conditions. One size fits most. Machine washable.",
        price: 400,
        category: "Accessories",
        productType: "accessory",
        stock: 30,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Garden", "Protection", "Essential"],
        freeShipping: true, shippingDays: "2-3",
    },
    {
        name: "Pruning Shears (Heavy Duty)",
        description: "Professional-grade pruning shears with sharp carbon steel blades. Cuts branches up to 20mm thick with ease. Ergonomic handle with safety lock. Essential for pruning roses, fruit trees, and shrubs.",
        price: 1200,
        category: "Accessories",
        productType: "accessory",
        stock: 15,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Tools", "Pruning", "Professional"],
        discount: 20,
        freeShipping: false, shippingDays: "3-5",
    },
    {
        name: "Drip Irrigation Kit (20 Plants)",
        description: "Automatic drip irrigation system for up to 20 plants. Includes timer, tubing, drippers, and connectors. Saves water by delivering it directly to plant roots. Perfect for balcony gardens and raised beds. Easy DIY installation.",
        price: 2500,
        category: "Accessories",
        productType: "accessory",
        stock: 8,
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
        images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600"],
        tags: ["Irrigation", "Smart", "Water Saving"],
        freeShipping: false, shippingDays: "4-6",
    },
];

async function seedAll() {
    console.log(`\n🌱 Seeding ${allProducts.length} products to Firestore...\n`);

    let count = 0;
    let categories = {};

    for (const product of allProducts) {
        product.vendorId = VENDOR_ID;
        product.createdAt = new Date();

        const docRef = await addDoc(collection(db, 'products'), product);
        count++;

        if (!categories[product.category]) categories[product.category] = 0;
        categories[product.category]++;

        const discountLabel = product.discount ? ` (${product.discount}% OFF)` : '';
        console.log(`  ✅ [${product.category}] ${product.name} - Rs. ${product.price}${discountLabel}`);
    }

    console.log(`\n📊 Summary by Category:`);
    Object.keys(categories).sort().forEach(cat => {
        console.log(`  ${cat}: ${categories[cat]} products`);
    });

    console.log(`\n🎉 Total: ${count} products added successfully!`);
    process.exit(0);
}

seedAll();
